# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Edgectl < Formula
  desc "CLI for Edgeworx Cloud"
  homepage "https://cloud.edgeworx.io"
  version "0.7.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Edgeworx/homebrew-edgectl/releases/download/v0.7.0/edgectl_0.7.0_macos_amd64.tar.gz"
      sha256 "7e4c1b28693a810c7fa23f7e79e78fc36bafd421260f0e277d0c3c4e3f629dd4"
    end
    if Hardware::CPU.arm?
      url "https://github.com/Edgeworx/homebrew-edgectl/releases/download/v0.7.0/edgectl_0.7.0_macos_arm64.tar.gz"
      sha256 "13cbcac56c434935fca90bf87d1638f09742c35bb1e22a4f6b9fd60b11032c73"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Edgeworx/homebrew-edgectl/releases/download/v0.7.0/edgectl_0.7.0_amd64.tar.gz"
      sha256 "2334e8c6614f547f2303c9a194c400fb16a1edd4ca97ef1b034009ba042ed72a"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Edgeworx/homebrew-edgectl/releases/download/v0.7.0/edgectl_0.7.0_arm.tar.gz"
      sha256 "b16987e66389578e5612da2c2b0ed2ed297e67f9e5d0a72da6d5e7ebe3ad49ba"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Edgeworx/homebrew-edgectl/releases/download/v0.7.0/edgectl_0.7.0_arm64.tar.gz"
      sha256 "0bee219272be5811e5897d73a80453cdcb1da1b1d4d08ef18fae8b73dc9803a2"
    end
  end

  def install
    bin.install "edgectl"
  end

  test do
    system "#{bin}/edgectl version"
  end
end
