# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Edgectl < Formula
  desc "CLI for Edgeworx Cloud"
  homepage "https://cloud.edgeworx.io"
  version "0.12.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Edgeworx/homebrew-edgectl/releases/download/v0.12.0/edgectl_0.12.0_macos_amd64.tar.gz"
      sha256 "742d008b2be55505d5a7cecb50963343c91f7cc432e12583cbad6a19ffbbf8d5"
    end
    if Hardware::CPU.arm?
      url "https://github.com/Edgeworx/homebrew-edgectl/releases/download/v0.12.0/edgectl_0.12.0_macos_arm64.tar.gz"
      sha256 "5fb3f422e334bdcdefe2831fe20bfe415caca48296dc728e4035fb811d6e6f1b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Edgeworx/homebrew-edgectl/releases/download/v0.12.0/edgectl_0.12.0_amd64.tar.gz"
      sha256 "d479904116ee69dd1ed2f147726d10bda11a8015f8aa29e0d2a21b548617b3cb"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Edgeworx/homebrew-edgectl/releases/download/v0.12.0/edgectl_0.12.0_arm.tar.gz"
      sha256 "aa081aee9e8514d04e4cdb2bb8755c25c8ced64c680601a3beb032dce3feec70"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Edgeworx/homebrew-edgectl/releases/download/v0.12.0/edgectl_0.12.0_arm64.tar.gz"
      sha256 "c798592565096a5b74525165a1eb930f00d9fc8e0a1d64c662906790d380f5a8"
    end
  end

  def install
    bin.install "edgectl"
  end

  test do
    system "#{bin}/edgectl version"
  end
end
